# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nook < Formula
  desc "Workspace organizer CLI for developers"
  homepage "https://github.com/lorenzo-vecchio/nook"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lorenzo-vecchio/nook/releases/download/v0.1.5/nook_0.1.5_darwin_amd64.tar.gz"
      sha256 "bb0e7d5affbd71d5aedfed18337c274d7cff8cf4a04a55e74ba44ea4bf5f9b9c"

      define_method(:install) do
        bin.install "nook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lorenzo-vecchio/nook/releases/download/v0.1.5/nook_0.1.5_darwin_arm64.tar.gz"
      sha256 "4a702004fcfe2e68205122648e56e236abbd0b44a5210cdca2fdf2c167fd7525"

      define_method(:install) do
        bin.install "nook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lorenzo-vecchio/nook/releases/download/v0.1.5/nook_0.1.5_linux_amd64.tar.gz"
      sha256 "8e49119194baf6081163040aa9a10cf5829338a43136d85772b31b63b4c5ec19"
      define_method(:install) do
        bin.install "nook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lorenzo-vecchio/nook/releases/download/v0.1.5/nook_0.1.5_linux_arm64.tar.gz"
      sha256 "ac85f0211779fdddea5da036a13643686db7b283d6be1f57b902fc045b958dd1"
      define_method(:install) do
        bin.install "nook"
      end
    end
  end
end
